### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by Brightlcz** [fiy2W/mri_seq2seq#1]
Hello, I would like to know how this visualization of the attention map is implemented, is it convenient to provide the relevant code. I hope you get better and better in your scientific research.

**Comment by fiy2W** [comment]
Thank you for your attention. There are two different "attention maps" in this repository.

For imaging-differentiation map $\mathcal{M}_d$ in "Synthesis-based Imaging-Differentiation Representation Learning for Multi-Sequence 3D/4D MRI", you can refer to the code here,
https://github.com/fiy2W/mri_seq2seq/blob/main/publications/src/seq2seq/README.md#imaging-differentiation-map
In addition, if you want to get $\mathcal{M}_d$ easily and automatically, you can try our nnSeq2Seq tool. Refer to the guide here,
https://github.com/fiy2W/mri_seq2seq/blob/main/nnseq2seq/docs/how_to_use_nnseq2seq.md#run-inference

For task-specific enhanced map (TSEM) in "An Explainable Deep Framework: Towards Task-Specific Fusion for Multi-to-One MRI Synthesis", you can refer to the code here,
https://github.com/fiy2W/mri_seq2seq/blob/main/publications/src/tsf/README.md#task-specific-enhanced-map-tsem

Let me know if you have any questions about our codes.
