### ISSUE TITLE
2D or 3D

### ISSUE THREAD

**Issue by DopamineLcy** [fiy2W/mri_seq2seq#3]
I appreciate your impressive work!
Were the results reported in the VQseq2seq conducted in 2D or 3D?
Thank you again and I am looking forward to your reply.

**Comment by fiy2W** [comment]
Thanks for your interest. Our model is trained with 2D slices. During inference, we first translate the test case slice by slice and then reconstruct it as a 3D volume to calculate metrics. You can find more details in the inference code. https://github.com/fiy2W/mri_seq2seq/blob/main/publications/src/vq/test/test_brats_vq_2d_metrics.py

**Comment by DopamineLcy** [comment]
Thank you for your prompt reply, which is really clear and helpful.

Best,
